<p>Mary is a completely normal human with no deviations from the standard human. She enjoys maintaining homeostasis, and finding entertaining things to do. She is a legal officiant in the state of Hawaii and a skilled craftswoman specializing in paper crafts. She has 2 cats that are the joy and also the agony of her being. Her favorite film series is Mad Max</p>
</p>If you would like to contact her she can reached on her personal banana phone at extention 'Sierrea Tango Oscar Papa'</p>
<p><b>Happy Harvesting.<b></p>
<img src="https://pbs.twimg.com/media/EBSi8dmVUAAl_tJ.jpg">