<p>Welcome to the <b>Home Page</b> and ty for dropping by! LL Cool J welcome you.</p>
<img src="llcoolj.jpg"/>
</p>Would you like to know the lyrics to Lido Shuffle? Yes, that one by Boz Scaggs? Look no further than the next few lines! You are very welcome.</p>
<p>Lido missed the boat that day
He left the shack
But that was all he missed
And he ain't comin' back
At a tombstone bar
In a juke joint car
He made a stop
Just long enough
To grab a handle off the top
Next stop Chi town
Lido put the money down
Let 'em roll
He said one more job ought to get it
One last shot 'fore we quit it
One for the road
Lido
Whoah oh oh oh
He's for the money
He's for the show
Lido's waitin for the go
Lido
Whoah oh oh oh oh oh
He said one more job ought to get it
One last shot 'fore we quit it
One more for the road
Lido will be runnin'
Havin' great big funnin'
Till he got the note
Sayin' tow the line or blow it
And that was all he wrote
He'll be makin' like a bee line
Headin' for the border line
Goin' for broke
Sayin' one more hit ought to do it
This joint ain't nothin' to it
One more for the road
Lido
Woah oh oh oh
He's for the money
He's for the show
Lido's waitin' for the go
Lido
Woah oh oh oh oh oh oh
One more job ought to get it
One last shot then we quit it
One more for the road
Lido
Woah oh oh oh
He's for the money
He's for the show
Lido's a waitin' for the go
Lido
Woah oh oh oh oh oh
One more job ought to get it</p>