<p> Lemon Pasta is a simple and delicate recipe, sure to impress your guests and your tastebuds!</p>
</p><b>Ingredients</b></p>
</p>12 ounces wide egg noodles</p>
<p>Zest and juice of 2 lemons; zest removed with a vegetable peeler and cut in very thin strips 1 inch long (see note)</p>
<p>1 cup heavy cream</p>
<p>Kosher salt, to taste</p>
<p>Lots of freshly ground black pepper</p>
<p><b>Directions</b></p>
<p> Bring a large pot of salted water to a boil. Add noodles, and stir to separate. Cook for 8 minutes, or until just barely tender (the noodles will cook a bit more in step 3, and you don't want mush). Drain, then return to the cooking pot.</p>
<p> Just before noodles are done, in a small saucepan combine the lemon zest, cream, salt, and pepper. Cook over medium heat for 2 minutes, or until cream comes to a boil.</p>
<p> Pour cream mixture over drained noodles, and add the lemon juice (you may want to start with 3 to 4 tablespoons and add to taste). Stir to coat. Cook over medium heat, stirring, until all the liquid is absorbed, about 1 to 2 minutes. Season with additional pepper, if desired.</p>
<p> <b>**</b> Note about lemon zest: Alternately, you can grate on a Microplane. The flavor will be a bit stronger as more flavorful oils are released this way, and you won't get the texture of the hand-sliced version. Dealer's choice!</p>
<p> This is a delicuious recipe that can be customized with all kinds of yummy yums, cheese? seafood? veggies? feel free to add and alter! Enjoy!</p>
<img src="https://f5petdcvm0-flywheel.netdna-ssl.com/wp-content/uploads/2019/04/pappardelle-cream-familystylefood.jpg" style = "width:50%">